server:
  port: 8080
  shutdown: GRACEFUL
spring:
#    static-path-pattern: /res/**            # 会导致welcome page失效
  web:
    resources:
      static-locations: classpath:/aa/   # 修改默认静态资源的文件夹
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true   # 开启浏览器请求参数的内容协商
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  # 文件上传大小限制
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.110:3306/index_test?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    druid:          # http://localhost:8080/druid/index.html
      aop-patterns: 'com.ityj.boot.*'    # 监控Spring Bean
      filters: stat,wall     # druid底层开启功能, stat(SQL监控功能), wall(防火墙功能)

      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false

      stat-view-servlet:    # 配置监控页功能
        enabled: true
        login-username: root
        login-password: root
        reset-enable: true

      web-stat-filter:   # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  aop:
    auto: false

  redis:
    host: 192.168.137.110
    port: 6379
    client-type: jedis

  # shutdown最大等待时间
  lifecycle:
    timeout-per-shutdown-phase: 30s

  boot:
    admin:
      client:
        url: http://localhost:8181
        instance:
          name: springboot-20220403
          prefer-ip: true


management:
  endpoints:
    enabled-by-default: true    # 开启所有的指标监控，包括shutdown
    web:
      exposure:
        include: '*'      # http://localhost:8080/actuator 查看所有支持的接口

  endpoint:
    health:
      show-details: always     # 开启健康检查详细信息

knife4j:
  enable: true    # http://localhost:8080/doc.html
  setting:
    language: en-US

mycar:
  price: 8888
  brand: BYD

debug: false

data:
  str: 字符串
  number: 233.22
  boolean: false
  list: Jack,Rose,Tom


path:
  fileupload: C:/upload/
  primary: /app/primary/project/
  secondary: /app/secondary/project/

#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml         # 默认为classpath*:/mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true       # 默认已经是true
