server:
  port: 8080

spring:
#    static-path-pattern: /res/**            # 会导致welcome page失效
  web:
    resources:
      static-locations: classpath:/aa/   # 修改默认静态资源的文件夹
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true   # 开启浏览器请求参数的内容协商
knife4j:
  enable: true    # http://localhost:8080/doc.html
  setting:
    language: en-US

mycar:
  price: 8888
  brand: BYD

debug: false

data:
  str: 字符串
  number: 233.22
  boolean: false
  list: Jack,Rose,Tom
